### PR TITLE
Paper engine memes

### PR DESCRIPTION
**Pull request by ninjanomnom**
burning_paper_1898680_by_stockproject1-d36cjgo

:cl: ninjanomnom
del: Let the paper engine rest in peace
/:cl:

### CODE REVIEW

**Comment by Keekenox** [comment]
No, don't do this. Not like this!!

**Comment by ninjanomnom** [comment]
It has to be done, he hasn't had real life in years. He would want it to be like this.

**Comment by Keekenox** [comment]
But he can't actually power the ship! It's just a neat trick we do to impress the top brass of nanotrasen to secure more funding for other projects!

**Comment by Cirrial** [comment]
Rest in pieces.

**Comment by IlyaIU** [comment]
that's not how you should fix it, look at grille code - there is specified procedure for tesla zapping

**Comment by ninjanomnom** [comment]
This is how tg fixed it, so I'm just going with that

**Comment by ninjanomnom** [comment]
Done in rebase, wtf though this is a simple fix that sat for almost a full month and didn't get merged.

**Pull request closed without merging**
