### PR TITLE
Adds a new ruin

### PR DESCRIPTION
**Pull request by Kmc2000**
@Qustinnus  Hi, if I did something wrong tell me.

The rest is a secret

:cl: Kmc2000
add: Added a new ruin
/:cl:

[why]: # This is for floyd's combat events thing, I had to pr it because of the fluff stuff I added.

### CODE REVIEW

**Comment by ike709** [comment]
Pics or it didn't happen.

**Comment by Qustinnus** [comment]
yes you made a pr out of it. Please send me the file on discord instead.

**Comment by Qustinnus** [comment]
now the ruin is in the files twice

**Comment by ninjanomnom** [comment]
Those walls are awful, what's the ingame sprite look like after smoothing?

**Comment by ninjanomnom** [comment]
Improve this and give it to floyd directly or wait until it's actualy used

**Pull request closed without merging**
