### PR TITLE
makes the front of the ship less autistic.

### PR DESCRIPTION
**Pull request by Qustinnus**
:cl: Floyd "juicyballs" mcbarley
tweak: makes the front of the trailblazer look less like ass.
/:cl:

https://i.gyazo.com/0e86786af7919837412207a03a5fe5b2.png
https://i.gyazo.com/3e3ead6a42aae58e89441aed134e1721.png

### CODE REVIEW

**Comment by monster860** [comment]
Fuck that now it looks more like ass

**Comment by Qustinnus** [comment]
less windows != looking like ass

**Comment by ike709** [comment]
Munitions is better than it was but still seems like a bunch of space is wasted unless you ordered a shitton of extra shells, and the HoP having a proper place for a line is great. I was going to do the HoP thing but you beat me to it.

**Comment by monster860** [comment]
image

**Comment by Qustinnus** [comment]
Thing is, munitions will get more machines in his room. There IS a shitton of wasted space in cargo and science and there's big reasons for that.

**Comment by Ecbrd** [comment]
you're killing me here with these screenshots
I can't even tell the difference!

**Pull request merged**
