### PR TITLE
Fix #2, RnD light fixture misplacement.

### LINKED ISSUE #2: Light fixture faces the wrong way in RnD
Faces east, there is no wall to the east.

### PR DESCRIPTION
**Pull request by hecksadecimal**
Fixes #2.

As described in the issue, one of the light fixtures in RnD was not placed correctly. It has been bumped one tile to the East and aligned against the wall.

### CODE REVIEW

**Comment by monster860** [comment]
That is a lot of changes for fixing the light.

**Comment by hecksadecimal** [comment]
I've attempted repeatedly to use the mapmerge tool, both in the TGM and DMM format. For some odd reason it still produces an unwieldy diff.

**Comment by monster860** [comment]
Here's a quick guide to redoing the PR:

1. Since you have 2 commits currently, do `git reset HEAD~2`
2. `git pull`
3. Try the changes again
4. `git push --force origin <branch name>`

Also, you shouldn't be using master branch for pull requests - Using non-master branches allows you to have multiple pull requests open at the same time.

**Comment by hecksadecimal** [comment]
mapmerge is still making massive changes to the file when I move the light. It's greatly improved from the default behavior of DreamMaker, but I don't understand why it's doing this.

**Comment by monster860** [comment]
Update your fork - `git fetch FTL13` `git checkout master` `git merge FTL13/master`

**Comment by hecksadecimal** [comment]
New pull request at #5

**Pull request closed without merging**
