### PR TITLE
Fix items spawned in security officer backpack

### PR DESCRIPTION
**Pull request by NIXC**
Fixes https://github.com/FTL13/FTL13/issues/747 
security officers now spawn with all the items listed there, no fuss. Kinda silly to spawn with ammo for a gun you dont have.

[Changelogs]: 
:cl: NINXE
fix: Security now spawns with a gun (for ye BOOLETS!), and a helmet.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
Remove the armor from there, our service uniforms are apparently armored after checking, Also I will PR an update that will allow them to hold their guns in the suit storage slot so if you want move the gun there and I will PR an update before that to allow the gun to actually be there.

**Comment by NIXC** [comment]
Alright, Ill remove the armor. Does it really matter if the gun starts in suit storage vs backpack? The smart player can always move it later.

**Comment by Qustinnus** [comment]
I think you had more in the backpack than what would normally fit, which is my only issue with it.

**Comment by NIXC** [comment]
I dont think it was overloaded (it was full if I recall) but I have adjusted it. The gun doesnt show up in suit storage when I run a round, I assume this is because it cant be there.

**Comment by Qustinnus** [comment]
Thats because it cant be there, thats where it originally was. I'll be uploading my PR hopefully today to resolve that

**Comment by Stealthkibbler** [comment]
Service jacket can't hold guns

**Comment by NIXC** [comment]
Qustinnus is going to change that in a PR before this one is merged

**Comment by ike709** [comment]
Stealth once again late to the party with information that is already known.

**Comment by Qustinnus** [comment]
@Stealthkibbler do u even read comments :^)

**Comment by ike709** [comment]
@Qustinnus I know they don't read existing GitHub Issues.

**Comment by Vivalas** [comment]
This doesn't fix anything since this is how it was before and it just doesn't spawn anything.

**Comment by Qustinnus** [comment]
@Vivalas can you not read comments?

**Comment by NIXC** [comment]
@Vivalas Alright then, Ill put it back in the backpack (Ill check backpack sizing first of course) and Qustinnus can move it to suit storage when suit storage is fixed

**Comment by ninjanomnom** [comment]
Just needs the changelog to be fixed

**Pull request merged**
