### PR TITLE
Actually adds corgi tails

### PR DESCRIPTION
**Pull request by stobarico**
Same as before, but now it actually works on:
- Lisa
- Dead Lisa
- Ian
- Dead Ian
- Shaved Lisa
- Dead Shaved Lisa
- Shaved Ian
- Dead Shaved Ian
(Didn't even know you could shave them)
(Didn't do it on puppies because technically their tails are small at that age, AND IT LOOKED REALLY FUCKING UGLY WHEN I TRIED TO DO IT)

### CODE REVIEW

**Comment by Qustinnus** [comment]
did you properly test it this time

**Comment by ike709** [comment]
150 hours of testing

**Comment by stobarico** [comment]
8feb383707da6d33763b12b8003616a2
Yisss

**Comment by Vivalas** [comment]
@Qustinnus Merge?

**Pull request merged**
