### PR TITLE
Makes sniper rounds a bit more formal in their names.

### PR DESCRIPTION
**Pull request by Vivalas**
Dunno if you guys are using auto-changelog or not, but here you go. The current sniper ammo boxes seemed a bit cheesy.

:cl: 
tweak: Makes sniper rounds more formal in their naming.
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
But I want to shoot someone with a "Zzzzzzzzz" round!

**Comment by CrAzYPiLoT-SS13** [comment]
I don't think we use autocl

**Comment by monster860** [comment]
Yes, we haven't set up autocl.

**Comment by Vivalas** [comment]
Will re-open

**Pull request closed without merging**
