### PR TITLE
MPRF: Rethemes the Necropolis

### PR DESCRIPTION
**Pull request by Kmsxkuse**
Closes #1298 
🆑 Joan
tweak: The Necropolis has been rethemed.
/🆑

### CODE REVIEW

**Comment by ninjanomnom** [comment]
Conflicts

**Comment by Kmsxkuse** [comment]
Ah shit, god damn it.

**Comment by Kmsxkuse** [comment]
I'll probably close this and redo this MPRF.

**Comment by Kmsxkuse** [comment]
Yeaaaaaaa. Something borked from working on this several MPRs back.

I pulled the MPRs that lead up to this and now it works.

**Comment by Kmsxkuse** [comment]
Holy shit. Okay. Im gonna do this again.

**Pull request closed without merging**
