### PR TITLE
Reliant; Building Better Worlds

### PR DESCRIPTION
**Pull request by Vasily2013**
Finally, after months of delay, a ship to make those who feel out of place on normal ships more comfortable is finally ready (I hope). 

The Reliant is intended to be a primarily combat oriented ship. Not only is it more combat focused than others may be, but this vessel is primed for convenient access from department to department, most of the time. Similar in size to the Butterfly, and borrowing some traits, this ship places less emphasis on civilian action, and more on the core of FTL13 missions, doing shooting and getting shot at. It also returns to a more Borg approach to design as landing the ship was not a design concern.

There are several features to help streamline the final preparations for combat. These features may include:
-Science accessible FTL and Shield generators
-Two, yes TWO, standard issue Mass Accelerator Cannons as the ship is issued
-Internal phase cannon hardpoints to remove those pesky EVA walks.
-Convenient escape pods for every department
-Fun and exciting semi-Extra vehicular tasks for xenobiologists or bored scientists to perform in order to increases research potential... and keep people busy...
-A self-regulating FOB atmospheric system that relies on planet atmosphere rather than a static supply.
-Centrally located Security doors for easy access to the civilian and military sections of the ship
-One standard issue ejector mechanism for purging undesirables from the ship
-A public holodeck for the inevitable emergency that medical can't deal with.
-Numerous EVA and hardsuits distributed between departments in addition to a standard EVA storage area
-A unique and secure vault location that provides excellent salvage access for retrieving un-used nuclear devices.
-an unlocked genetics air alarm to allow medical staff to easily and quickly clone plasmamen simply by venting oxygen from the room... although I doubt they'll be smart enough to do this.

As it stands Reliant is intended to enter the normal fleet rotation, and hopefully can make metastation players feel at home with it's square, boxy feeling. The Reliant should offer new, and relatively unique opportunities for gameplay around the ship with its compact design. Engineering mains get a real kick in the backside with a brand new, and unique in the fleet hybrid TEG/radiation engine design. 

why: With the current ship rotations there is a limited availability for small ships that don't require tedious solar setups. It provides a ship layout that, in theory, could speed up round times. It reduces the risk of engineers falling off the ship due to a miscommunication about FTL jumps. Finally it allows me to put forward a, to my knowledge, unique SM engine design that engineering mains can play with.

Edit: Newly uploaded images
reliant noarea 2
reliant area 2

### CODE REVIEW

**Comment by GoatMonarch** [comment]
Glad to see you've gotten a PR up and running, pardon me for running slow. I'll just start to count up several issues I've found merely by looking around on your map. 

As always feel free to ping pong me on discord when I am not busy and I'll be more specific with anything if need be.

Lacking:
Bartender has no shotgun.

The bar has no bar sign, you sick heck!

There's a lack of cameras in the hallways, might be worth checking around the ship as an AI ingame. (Do keep in mind some cameras breaks down at round start for the AI.)

While I know cargo is equally as usefull as the nipple on a man, they still want a request console for the public so they can feel usefull.

The janitor does not have any space cleaner, you monster. They also does not have a faucet to refill their bucket from.



Issues worth changing:
The captain's quarters southern walls are two reinforced walls thick, you could very easily push it down and implement the captain's guncase down by the entrance then, removing the need for the additional gun inside the captain's locker.

The cargo shuttle will run out of power fairly fast unless you implement an APC or attain a higher capacity cell for the APC given that it has a relay as well now. Might be worth pushing up the max power stored within that APC.

The flooring for the engines, and other objects out in space has atmos on them. You'll need to remove said atmos.

It might be worth reconsidering the fact you've given a public access mass driver to anybody with a pulse in the middle of a hallway.

The fake nuclear disk code wise (if I remember correctly) will have pinpointers point towards to it, might be worth testing.

While a cute idea, the clown baton is probably something you should place within brig. You have to remember when implementing items for clowns it that both the braindead gluessnifers, and actually funny clowns will have the same tools.
Reskinning a baton will also unironically turn more into a mime item since clowns still has the clumsy gene, making security equipment risky for clowns.

You could potentionaly re-route disposals so the trash will go towards the YEET machine.

Disposals are two directional, and not one directional. Not important but it grinds my gears.

AI upload bwoink mine is not layered correctly, and will be visible atop of the airlock at all times.

**Why would you give the MO a security hardsuit, but not security?** The MO is also lacking a bomb suit for his eventual fuckup.

The engineroom path towards tech storage is zoned wierd, you'll probably want to make sure the SM engine area only covers the SM area.

You should implement an airlock for tech storage from the hallway. The RD is meant to have tech storage access. Don't do the same mistake as I did on the honkerprise.

EVA is actually a high security area, and should have reinforced walls around it.

There is no publicly accessible area for coins to the public.

The clown has no multi-tool. Expect alot of wirecutter hacking unless they move their honkey arse to tool storage.

I suspect that having two layers of shields around the ship will make them look wierd when they are turned on ingame.


Removal:

There's two instances of mini fans located under the Xenobio construction airlock access.

**Comment by Vasily2013** [comment]
> Glad to see you've gotten a PR up and running, pardon me for running slow. I'll just start to count up several issues I've found merely by looking around on your map.
> 
> As always feel free to ping pong me on discord when I am not busy and I'll be more specific with anything if need be.
> 
> Lacking:
> Bartender has no shotgun.
> 
> The bar has no bar sign, you sick heck!
> 
> There's a lack of cameras in the hallways, might be worth checking around the ship as an AI ingame. (Do keep in mind some cameras breaks down at round start for the AI.)
> 
> While I know cargo is equally as usefull as the nipple on a man, they still want a request console for the public so they can feel usefull.
> 
> The janitor does not have any space cleaner, you monster. They also does not have a faucet to refill their bucket from.
> 
> Issues worth changing:
> The captain's quarters southern walls are two reinforced walls thick, you could very easily push it down and implement the captain's guncase down by the entrance then, removing the need for the additional gun inside the captain's locker.
> 
> The cargo shuttle will run out of power fairly fast unless you implement an APC or attain a higher capacity cell for the APC given that it has a relay as well now. Might be worth pushing up the max power stored within that APC.
> 
> The flooring for the engines, and other objects out in space has atmos on them. You'll need to remove said atmos.
> 
> It might be worth reconsidering the fact you've given a public access mass driver to anybody with a pulse in the middle of a hallway.
> 
> The fake nuclear disk code wise (if I remember correctly) will have pinpointers point towards to it, might be worth testing.
> 
> While a cute idea, the clown baton is probably something you should place within brig. You have to remember when implementing items for clowns it that both the braindead gluessnifers, and actually funny clowns will have the same tools.
> Reskinning a baton will also unironically turn more into a mime item since clowns still has the clumsy gene, making security equipment risky for clowns.
> 
> You could potentionaly re-route disposals so the trash will go towards the YEET machine.
> 
> Disposals are two directional, and not one directional. Not important but it grinds my gears.
> 
> AI upload bwoink mine is not layered correctly, and will be visible atop of the airlock at all times.
> 
> **Why would you give the MO a security hardsuit, but not security?** The MO is also lacking a bomb suit for his eventual fuckup.
> 
> The engineroom path towards tech storage is zoned wierd, you'll probably want to make sure the SM engine area only covers the SM area.
> 
> You should implement an airlock for tech storage from the hallway. The RD is meant to have tech storage access. Don't do the same mistake as I did on the honkerprise.
> 
> EVA is actually a high security area, and should have reinforced walls around it.
> 
> There is no publicly accessible area for coins to the public.
> 
> The clown has no multi-tool. Expect alot of wirecutter hacking unless they move their honkey arse to tool storage.
> 
> I suspect that having two layers of shields around the ship will make them look wierd when they are turned on ingame.
> 
> Removal:
> 
> There's two instances of mini fans located under the Xenobio construction airlock access.

Fixed/addressed in order
-Bartender now has a shotgun
-Bar now has signs
----Will update after AI camera test
-Public request console added to the nipple
-Janitor now has a sink, water tank, and space cleaner.
-Captain's quarter's wall is two thick to prevent weak spots to the hallway.
-Cargo shuttle APC, in theory, has ten times more power.
-The engine core flooring is airless, the core airlock is not. This is to prevent harm to careless engineers.
-turfs that previously had air in space no longer have air.
-Mass driver access was tweaked after I walked into the room during a clown test.
----Will update after pinpointer test
-Clown baton moved to security, leading to funnier beatings.
-I could, but that would require work. I'm happy with the grinder. Maybe later.
-Omni-directional disposals request can be blamed on the whisp for having one of the more compact disposals systems.
-Bwoink mine moved and hidden.
-Security has hardsuits, look harder. MO was also given a sec hardsuit based on the likelyhood of them having to fix holes being high, or boarding missions.
-Engine SM area reduced to only cover the turfs for the APC and air alarm
-Tech storage now has a door to the hallway
-r-walls placed instead of regular walls
-Coin press added in cargo maint
-Clown given a multi-tool
-Personally the shields look good to me. Befitting of a ship designed for combat.
-One fan removed from science airlock.

**Comment by crossedfall** [comment]
I can't currently think of a better way to implement what you're trying to do on the current FOB but I gotta say I really don't like this. 
image

I'd also recommend adding a label to the digital valve since it's purpose is not inherently obvious

**Comment by Vasily2013** [comment]
> I can't currently think of a better way to implement what you're trying to do on the current FOB but I gotta say I really don't like this.
> 
> I'd also recommend adding a label to the digital valve since it's purpose is not inherently obvious

-Adjusted back of FOB so it no longer has the shortest wings in history when loaded in game.
-renamed valve to "air feed cutoff"
mining atmos 2

**Comment by NIXC** [comment]
Alright, I know some of this has already been fixed from discord, but wanted to put the full list here just for record purposes.  In no particular order:

- No lights in AI chamber
- The pipe in the middle of the fob looks really out of place
- Cells don't have flashes in security
- Cell numbers start at 2
- No sec robots
- Atmospherics piping has lots of above and below floor pipes, it doesn't look good in my opinion. Should probably be all above.
- I strongly dislike that you put lockers on top of suit storage. The suit storage is hard to access, and from a RP perspective it doesn't make any sense.
- There is an empty suit storage in medical hidden under a locker.
- Beacons don't appear to work.
- Space is not ftl space, I dunno if that makes a difference but I would include it just because.
- No toilet/bathroom.
- Cameras all have random names. This makes it hard for AI's who cant jump to specific cameras, and impossible for anyone else to use camera consoles.
- I find your placement of the beds some what questionable, but that's opinion.

**Comment by Vasily2013** [comment]
-AI already had light fixture
-Valve moved again
-Added flashes to sec
-AI core used to be a cell and I'm lazy.
-Added sec robots
-Pipes now visible for less spooks
-The main issue with lockers and suit storage is space. I'll see if there are some other spots where I can cram lockers into.
-replaced empty suit storage with full eva suit as intended
-Then I don't understand how beacons work and nobody's explained it to me.
-space under shields is ftlspace. I don't know if it makes a difference either. If there is a problem I can change that.
-Cameras have random names because cameras are a pain in the butt, i'll start working on naming the cameras... eventually.

**Comment by Vasily2013** [comment]
Cameras now have names, and lockers have been shifted to less convenient locations.

**Comment by GoatMonarch** [comment]
@Vasily2013 I think the progression for this PR has gone fairly well. I think the last thing you need to report is to play test as an AI and check over the map, given there is no shitty cammera coverage I'll give it a thumbs up for a player test.

**Comment by Vasily2013** [comment]
Okay, made sure that AI cameras have proper coverage, added one to the escape shuttle, and also noticed that NIN was right and there was no light in AI core. There is also, subsequently, a light in the AI core.

**Comment by GoatMonarch** [comment]
I've spoken with Nin over discord and will now approve of this PR being test merged. Congratulations on geting it thru boii

**Comment by crossedfall** [comment]
Has been fine through the test merges and has received fairly consistently positive feedback. Merging as part of our EoL

**Pull request merged**
