### PR TITLE
Redesigned Bar/Kitchen area.

### PR DESCRIPTION
**Pull request by Ecolli**
Added MO and BO manuels and motion camera near Armory maintenance.

:cl: Ecolli
tweak: Tweaked munitions delivery outlet
add: Added motion cameras to maintenance next to armory
tweak: Complete overhaul of bar/kitchen area
add: Add MO and BO manuals to relative areas
fix: Fix weapon signs to be on correct layer
/:cl:

### CODE REVIEW

**Comment by Vivalas** [comment]
While I liked the old space-tunnel design thing, this looks much better. :+1:

**Comment by Vivalas** [comment]
Bar looks good but looking over the kitchen I see a few issues 

First of all that sink is in a weird spot, might wanna switch it with the dinnerware vendor, so the sink isn't in a corner like that. The picture also doesn't show any food in the three refrigerators you added. Make sure they have the basics, some flour, meat, and sugar.

**Comment by EvilJackCarver** [comment]
Hey, if it's not too much trouble to ask, would it be possible to get a camera in the spacepod hangar as well?

**Comment by monster860** [comment]
The lockers should start with the required shit @Vivalas @Ecolli

**Comment by Ecolli** [comment]
The fridges come with food in them by default but I think if I can find food and put them on top of the fridge it'll spawn them inside when the map is created if I remember right. 
maybe Ii can switch the sink with the microwave? either way it has to go on a "upper wall" the sideways sink looks funky to me. 

    On Monday, December 12, 2016 5:29 AM, Vivalas <notifications@github.com> wrote:
 

 Bar looks good but looking over the kitchen I see a few issuesFirst of all that sink is in a weird spot, might wanna switch it with the dinnerware vendor, so the sink isn't in a corner like that. The picture also doesn't show any food in the three refrigerators you added. Make sure they have the basics, some flour, meat, and sugar.—

**Pull request merged**
