### PR TITLE
Deletes non-FTL13 maps

### PR DESCRIPTION
**Pull request by ike709**
:cl: ike709
del: Removed all non-FTL13 maps. Rest in peace, /tg/ stations.
/:cl:

I'm not sure if generic should be removed or not. Let me know if removing that one breaks things.

### CODE REVIEW

**Comment by ninjanomnom** [comment]
932k line removals, wew

**Comment by ike709** [comment]
@ninjanomnom That's tgm for you.

**Comment by Vivalas** [comment]
Conflicts and @monster860 not quite sure which of these z# files are relevant.

**Comment by ike709** [comment]
I'll just remove the generic file from this PR then.

**Comment by ike709** [comment]
Fuck these conflicts. See: https://github.com/FTL13/FTL13/pull/656

**Pull request closed without merging**
