### PR TITLE
REEEEE NEW SOUNDS FOR THE MAC CANNON! REEEEE

### PR DESCRIPTION
**Pull request by Lambrovski**
Yep, this seems like a good description.

### CODE REVIEW

**Comment by Lambrovski** [comment]
REEEEEE I HAVE NO IDEA HOW TO REMOVE FILES FROM PULL REQUESTS REEEEEE
REEEEEE WHAT ABOUT I JUST SEND YOU FILES ON MAIL REEEEE

**Comment by Lambrovski** [comment]
Help, what is happening.

**Comment by monster860** [comment]
Take a backup of all the new sounds, then do this:

```
git fetch FTL13
git reset --hard FTL13/master
git push --force origin master
```

Then try to add the sounds to the repo again

**Comment by Lambrovski** [comment]
What

**Comment by Qustinnus** [comment]
what the fuck is this lambich.


just send me the fucking files holy fuck.

**Comment by Lambrovski** [comment]
Help

**Comment by Lambrovski** [comment]
Can you just cancel commits or some shit?

**Comment by Qustinnus** [comment]
no you dildo just make a new branch from the master and move the sounds there holy fuck

**Pull request closed without merging**
