### PR TITLE
Directional stairs with bottom and top sections

### PR DESCRIPTION
**Pull request by stobarico**
D I R E C T I O N S
5e3e1e15baa70022ff42cd815cac8dc0
LET'S GOO

### CODE REVIEW

**Comment by Partheo** [comment]
Woah dude

**Comment by Ecolli** [comment]
Gimmie gimmie gimmie!!

**Comment by RemBestWaifu** [comment]
is that bay

**Comment by stobarico** [comment]
It's from Polaris

**Comment by Cdey78** [comment]
First step towards multi-Z? Good stair sprites?

**Comment by Qustinnus** [comment]
no first step to multi z is getting kor to add proper height management for Z levels so i can add procs for multi z

**Comment by Cdey78** [comment]
I was referring to the fact that the stairs kind of look like they're ascending/descending into darkness.
It was also a joke.

**Pull request merged**
