### PR TITLE
XDDDDD

### PR DESCRIPTION
**Pull request by Kmc2000**
@Qustinnus 

Yeah here you go monkies without pants

:cl: Kmc2000
add: Added ERP options for monkies by making a type that has no pants on.
/:cl:

### CODE REVIEW

**Comment by Cirrial** [comment]
I mean, it would make a lot more sense for wild monkeys on a different planet to perhaps not all be geared up with space station nappies or whatever the hell it is they're wearing.

**Comment by Vivalas** [comment]
@Kmc2000 Pictures please.

**Comment by Kmc2000** [comment]
Do you have literally no imaginition lol?

**Comment by Cirrial** [comment]
If you won't do it...

monkey

**Comment by Kmc2000** [comment]
L..lll...lewd

**Comment by Vivalas** [comment]
Why does that monkey on the bottom left have metal hemroids in his ass?

**Comment by Cirrial** [comment]
Looks like lazy spritework to me, the pixels are identical to the ones on the base monkey sprite.

**Comment by Stealthkibbler** [comment]
it's literally a monkey not wearing a diaper, they dont exactly have to be unique or different from the normal ones. the only problem is the metal hemorrhoids that viv pointed out.

**Comment by Cirrial** [comment]
No, I mean those two pixels are from the original diaper. That's why I said lazy spritework.

**Comment by ninjanomnom** [comment]
Stale for too long, message me if you ever want this reopened @Kmc2000

**Pull request closed without merging**
