### PR TITLE
Clanker no longer supports WWE action

### PR DESCRIPTION
**Pull request by Stealthkibbler**
replaces bar tables with normal ones

:cl: Stealthkibbler
fix: Clanker bar tables replaced with normal ones, you can no longer suplex your way to victory
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
if you're going to do this why dont you remove all the loot spawns while you're at it u tit

**Comment by Stealthkibbler** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by ninjanomnom** [comment]
This doesnt look map merged

**Comment by Stealthkibbler** [comment]
>using map merger

do you want me to get an aneurysm

**Comment by ninjanomnom** [comment]
just use fastdmm, not merging this until it's map merged

**Comment by Qustinnus** [comment]
how else do you think we can fucking use this you tit

**Comment by Stealthkibbler** [comment]
I dont know how to mapmerge or use fastdmm, Injaz did all of that shit when I handed the map over to him

**Comment by Qustinnus** [comment]
its literaly the easiest thing in this world

**Comment by Stealthkibbler** [comment]
yeah maybe for you, last time I even looked at it I almost formed a tumor in my brain

**Comment by Qustinnus** [comment]
>before you edit your map run backup maps
>edit your map
>mapmerge as TGM
>select your map


Its literaly that easy

**Comment by Stealthkibbler** [comment]
none of that makes any sense to me

**Comment by Stealthkibbler** [comment]
where is backup maps

**Comment by Qustinnus** [comment]
in tools

**Pull request closed without merging**
