### PR TITLE
Adds conveyor belts to the station

### PR DESCRIPTION
**Pull request by Qustinnus**
🆑 Qustinnus
rscadd: Adds conveyor belts to station
/🆑

slightly worried that i fucked up mapmerging but I'm not sure how to check.

### CODE REVIEW

**Comment by bauen1** [comment]
You fucked up the map merging, if there are >100 changes you most likely have fucked up

**Comment by Qustinnus** [comment]
I know but I don't know /what/ I fucked up. It's confusing as fuck.

**Comment by Qustinnus** [comment]
Re-mapmerging literaly doesn't change shit.

**Comment by monster860** [comment]
You didn't fuck up anything. The map on the base repo was not in TGM format

**Comment by bauen1** [comment]
Sorry then

**Comment by monster860** [comment]
I'm gonna need to fix a thing

**Comment by Qustinnus** [comment]
godspeeds with the shields.

One reccomendation is just flatout disabling them when you dock with stations, Combat shouldn't be possible when you're docked anyways if we're following Ecolli's vision (how the hell can you dodge and aim at them while docked? ;^))

**Comment by Vivalas** [comment]
Docking with shields up sounds like a dumb idea anyways.

**Comment by monster860** [comment]
Shields aren't the problem here. The problem is the shuttle system.

**Pull request merged**
