### PR TITLE
Adds a New Map, the NSV Ineese

### PR DESCRIPTION
**Pull request by IndusRobot**
[Changelogs]: # (Please make a changelog if you're adding, removing or changing content that'll affect players. This includes, but is not limited to, new features, sprites, sounds; balance changes; map edits and important fixes)

FOBshuttle's big brother. 

This is a map I've worked on and off for eight months or so. It's got some cool new bits and bobs, some fun easter eggs, and tons of hats to collect! It's about the size of the old Astraeus but a little bit wider in some places. It's designed for the relatively low population FTL13 is sitting in right now. Ideal crew count is about 10 - 25 people on this ship.

Expect lots of bugs as it hasn't been tested much. Just create a new issue on the GitHub tracker or ping me somewhere in Discord.

Here's a map, if that helps. 

ineese-1

:cl: IndusRobot
add: Added a map, the NSV Ineese
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)

### CODE REVIEW

**Comment by LordWalnut** [comment]
👍 S 👍 P 👍 E 👍 E 👍 D 👍 M 👍 E 👍 R 👍 G 👍 E 👍

**Comment by Gobblesmack** [comment]
tuning fork or closed pr

**Comment by Qustinnus** [comment]
sure why not

**Comment by Ecolli** [comment]
Can't wait to check out your new map! 

Maybe someday I'll stop being lazy and update the Tuning Fork as well.

**Pull request merged**
