### PR TITLE
Adds an actual landmark to notify admins and ghosts about stations

### PR DESCRIPTION
**Pull request by ike709**
:cl: ike709
tweak: Ghosts will now see a proper notification about stations being generated, rather than a pulse rifle prize notification.
/:cl:

Does #632 properly. Replaced the prize pulse rifle with a normal pulse rifle and adds a landmark which notifies admins and ghosts (teleportation included) about stations being generated.

### CODE REVIEW

**Comment by ike709** [comment]
God fucking damn it I used fastDMM what happened?

**Comment by Qustinnus** [comment]
@monster860 AAAAAAAAAAAAAAAA FASTDMM IS BURNIN DOWN

**Comment by ike709** [comment]
Did I goof the line endings again or something or is fastDMM borked?

**Comment by ike709** [comment]
No it's definitely converted to TGM so I dunno what the issue is. Is it the line endings?

**Comment by Vivalas** [comment]
Can't merge this until mapmerged.

**Comment by ike709** [comment]
@Vivalas I used fastDMM. Can you tell me how it broke?

**Comment by ike709** [comment]
@Vivalas See: https://github.com/FTL13/FTL13/pull/689

**Pull request closed without merging**
