### PR TITLE
Porting TG's latest MC to FTL13

### PR DESCRIPTION
**Pull request by Cirrial**
At Ike's request, here is a combination port and refactor to speed up performance. This is a messy change.

Some better information as to how this boosts efficiency:

Baseline (unmodified) MC performance:

Baseline performance profiling statistics, ordered by Realtime
Baseline performance profiling statistics, ordered by Total CPU

Ported MC (this PR) performance:

Modified performance profiling statistics, ordered by Realtime
Modified performance profiling statistics, ordered by Total CPU

:cl:
experiment: Merging TG's latest master controller to try and improve setup times and other lag
/:cl:

### CODE REVIEW

**Comment by Cirrial** [comment]
there's a ton of issues but there's probably no point in closing and resubmitting it, I'm just gonna paste what Ike said was wrong so I can come back to this and fix it (also it has merge conflicts, wtg me)

- unnecessary constants that aren't being used, find what aren't being used and prune them
- double check how the LoadingMap stuff affects the code
- consistency - replace other subsystem New()s with SUBSYSTEM_DEF

**Comment by ike709** [comment]
image
image

**Comment by Cirrial** [comment]
fixed the merge conflicts, but the other issues are still outstanding

**Comment by Cirrial** [comment]
going to close this again until it's fixed for definite

**Comment by Cirrial** [comment]
added the loadingmap calls as proper functionality, the idea I believe is that instead of simulating atmos differences during map load (the most expensive init) it defers them to after map loading is complete, but while other subsystems are loading

**Pull request closed without merging**
