### PR TITLE
[AS READY AS IT'S GETTING] Gas Miners

### PR DESCRIPTION
**Pull request by ike709**
@Qustinnus Have a happy April Fools' Day.

This is potentially before April Fools' Day depending on timezones, so I have another PR ready for later :^)

:cl: ike709
add: Ported gas miners from /tg/
/:cl:

This is my first time using Injazz's method of ~~stealing~~ porting commits, so let's see if I fucked anything up.

Ports gas miners from /tg/. Credit to kevinz000. They basically just generate a specified gas when powered and their atmos container isn't over pressurized.

### The goal is to make them only work while orbiting gas giants, but I don't know how to do that so I won't be able to finish this until someone helps me. I also don't know if this is balanced at all, so I'd love some feedback.

I left the water vapor miner in because ninja is adding water vapor, but I don't know if it needs a gas miner.

TODO:
- [x] Make gas miners only work while orbiting a gas giant.
- [x] ~~Balance gas miners.~~ In a later PR, after ingame feedback.
- [x] Add gas miners to the maps.
- [x] Test gas miners after the above changes. They definitely work.
- [x] ~~Reduce the amount of gas atmospherics has at roundstart, maybe.~~

Things I won't be doing, at least in this PR:
- ~~Control console~~ Actually, I'll just add them to the tank consoles in atmos. But not in this PR.
- Making them buildable/deconstructable
- Make the amount of gas created scale with amount of power inputted. 

Looks pretty much identical on all three maps, so all you get is a pic from Aetherwhisp
image

### CODE REVIEW

**Comment by Vivalas** [comment]
I think this needs to be discussed with @Ecolli about balance.

**Comment by Vivalas** [comment]
This needs more depth than just "turn on gas miner and get gas", I kinda want to add different gas giant types and maybe a feature like flying into the atmosphere, I might add that when I do the planetary landing sequences.

**Comment by ike709** [comment]
It's definitely horribly unbalanced @Vivalas except in an underpowered way. It very slowly makes any gas. And if you want each gas planet to have different gasses, I dunno how to do that.

**Comment by Ecolli** [comment]
Possibly make the environment dangerous. That way there's a trade off of getting free gas but endangering the ship while being within the atmosphere for collection. (I definitely suggest the SHIP be required to drop into the atmosphere to collect the gas or risk is being OP but maybe someone else has a better idea)

**Comment by ike709** [comment]
I don't know how to do any of that either, but I could just remove the gas miners from the map, then this PR can be merged and someone else can have fun with improving it.

**Comment by Qustinnus** [comment]
@Ecolli you realize this is not OP because right now we just have an unlimited supply of gas, right??

**Comment by Ecolli** [comment]
@Qustinnus Anyone manage to figure out whats causing that bug yet?

**Comment by Qustinnus** [comment]
t h a t s  n o t  a  b u g  e c o l l i

**Comment by Qustinnus** [comment]
t h a t s   h o w   a t m o s   w o r k s

**Comment by Ecolli** [comment]
NVM, I thought it was tied to the issues that are happening with FTL drive and other equipment using up plasma but not working. there been a bug reported about it lately and I thought they were tied.

**Comment by ike709** [comment]
Since I don't know how to do the majority of improvements/features/whatever that have been suggested, I removed the gas miner from the maps. Either this is merged and someone else can improve it later, or this can be closed forever. @Vivalas @Ecolli @Qustinnus

**Comment by ninjanomnom** [comment]
I'll fix them in my engineering QoL update after I finish the engine

**Comment by Vivalas** [comment]
I'm in favor of merging this with removal from the map pending review.

**Comment by Ecolli** [comment]
Agreed. I think we can develop a better way to implement gas miners than what we have so far. Seems a bit rushed, IMO.

**Pull request merged**
