### PR TITLE
We get lazy (again)

### PR DESCRIPTION
**Pull request by ike709**
:cl: ike709
add: Ported LAZYINITLIST, UNSETEMPTY, LAZYLEN, LAZYADD, LAZYREMOVE, and LAZYACCESS to make future ports easier.
/:cl:

I added these in a PR that did a bunch of other stuff and got reverted. So now I'm just including this, and not replacing anything in the code with it yet. It's the latest from /tg/ _lists file. Also renamed lists.dm to _lists.dm

Since it's probably hard to find, the new shit is at the bottom of the file.

### CODE REVIEW

**Comment by ike709** [comment]
@monster860 What do you mean it changes the line endings?

**Comment by IlyaIU** [comment]
@ike709 change LF to CRLF

**Comment by ike709** [comment]
@IlyaIU That means nothing to me.

**Comment by ike709** [comment]
New PR time

**Pull request closed without merging**
