### PR TITLE
Atmos heater

### PR DESCRIPTION
**Pull request by julian94**
:cl: julian94
add: New heater in atmos.
tweak: I had to move a few pipes to make things fit.
/:cl:

screenshot 2016-09-01 04 23 23

### CODE REVIEW

**Comment by monster860** [comment]
I'd rather have it connect directly to the supply loop

**Comment by julian94** [comment]
Yeah I can do that. But then we'll probably need more of 'em.

**Comment by monster860** [comment]
Remember, spessmen pipes aren't realistic: An entire connected pipenet references the same gas-mixture datum for every pipe.

**Comment by julian94** [comment]
It's now directly connected to the distribution loop.

**Comment by monster860** [comment]
Pics?

**Comment by julian94** [comment]
Can't get you any pics before monday, but it looks quite similar except
that the freezer is connected on the right side instead of the left.

**Comment by CrAzYPiLoT-SS13** [comment]
Inb4 traitor atmos tech kills whole ship using the heater.

**Comment by julian94** [comment]
The slowesr way ever.

**Comment by julian94** [comment]
Heater 19 51 23
Here you go.

**Pull request merged**
