### PR TITLE
Renames Warden to Master-at-Arms

### PR DESCRIPTION
**Pull request by ike709**
:cl: ike709
tweak: Warden has been renamed to Master-at-Arms.
/:cl:

I tested the icons and they all seem to be fine. Didn't alter any sprites, just renamed them.

### CODE REVIEW

**Comment by ninjanomnom** [comment]
...why?

**Comment by ike709** [comment]
@ninjanomnom Send all complaints to @Qustinnus I'm just doing their bidding.

**Comment by Qustinnus** [comment]
Because we don't deal as much as prisoners as we will with dealing out and keeping track of weaponry.

**Comment by ike709** [comment]
I'm stupid and I fixed the conflicts without renaming the areas to "masteratarms" again. One moment...

**Comment by ike709** [comment]
w e w l a d

conflicts resolved

**Pull request merged**
