### PR TITLE
Fixes the readme and makes it more accurate

### PR DESCRIPTION
**Pull request by ike709**
Before:
image

After:
image

### CODE REVIEW

**Comment by ninjanomnom** [comment]
ehhhh, I'm not sure how I feel about more than 1 joke badge

**Comment by ike709** [comment]
>implying they're joke badges and not actual representations of post-rebase code

**Comment by ninjanomnom** [comment]
@Vivalas oy that's not your call to make

**Comment by ike709** [comment]
w e w l a d

maintainer drama

**Comment by Vivalas** [comment]
Hey these are nice ya wanker.

**Comment by ninjanomnom** [comment]
that's an opinion you can have but with subjective changes like this there needs to be agreement rather than just merging

**Pull request merged**
