### PR TITLE
Changes Central Command to Fleet Command

### PR DESCRIPTION
**Pull request by tylerh95**
:cl: Fleeterizing
tweak: tweaked CentCom ID cards to be FleetComm ID cards
twear: Default FleetComm rank from General to Admiral
tweak: Updates a lot of flavor text and announcement instances from Central Command / CentCom to Fleet Command / FleetComm
spellcheck: fixed a grammar issue
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
Whyyyyyy

**Comment by CrAzYPiLoT-SS13** [comment]
All my yes.

**Comment by monster860** [comment]
Fleet command doesn't shorten very well.

**Comment by Nickvr628** [comment]
Fleet command shortens to Flcom. Sounds good to me.

**Comment by monster860** [comment]
I don't agree with this change, because it's literally renaming central command to fleet command, and central command is pretty much the entity that commands everything.

Fleet command wouldn't include stations.

**Comment by tylerh95** [comment]
That is true, fleet command would not include stations. I thought we we're trying to go for a more unique / changed lore, but if we want to stick with Central Command, that's cool too.

**Comment by Qustinnus** [comment]
i dont care either way but monster's argument makes sense.

aslong as i dont have to change any voice lines

**Pull request closed without merging**
