### PR TITLE
Ian now has a tail

### PR DESCRIPTION
**Pull request by stobarico**
ce975320fc1048fc5129594004c9660d
Adds tails to:
- Normal Ian body
- Deathsquad Ian body
- Cardboard Robot Ian body

### CODE REVIEW

**Comment by RemBestWaifu** [comment]
Can you make it darker on the yellow tip and White tip?

**Comment by praisenarsie** [comment]
test it first to see if any clothing isnt borked

**Comment by stobarico** [comment]
It has been tested

**Comment by Qustinnus** [comment]
are you going to change anything or is it ready? @stobarico

**Comment by Qustinnus** [comment]
add a changelog

**Comment by stobarico** [comment]
there

**Pull request merged**
