### PR TITLE
Time for a drone to escape from being a hat is greatly reduced

### PR DESCRIPTION
**Pull request by ike709**
:cl: ike709
tweak: Drones can now escape from cruel crewmembers much faster. You monsters.
/:cl:

Reduced time it takes a drone to jump off someone's head to 1/2 the time because being worn as a hat against your will is really fucking annoying when you're going out of your way to fix shit.

### CODE REVIEW

**Comment by Vivalas** [comment]
Iunno, kinda seems like a NO FUN ALLOWED type thing.

**Comment by ike709** [comment]
@Vivalas I want you to go play as a drone for 2 or 3 rounds, because you're right. It is no fun, for drones.

**Comment by Qustinnus** [comment]
seems like a bit of a grudge PRv though. 1/5th is too much.

**Comment by ike709** [comment]
Changed it to 1/2.

**Comment by Vivalas** [comment]
Alright 1/2 is more tolerable. Most of the time you can ninja out while they're talking or something so :+1:

**Pull request merged**
