### PR TITLE
Update toolsmerge-upstream-pull-request.sh

### PR DESCRIPTION
**Pull request by LetterJay**

### CODE REVIEW

**Comment by Qustinnus** [comment]
@monster860 I dont know anything about things like this.

**Comment by ninjanomnom** [comment]
You don't use this atm and if you eventualy set up the bot again you'll want the updated version. This should be fine.

I'd check to make sure it's up to date though.

**Comment by Vivalas** [comment]
Is this still relevant?

**Comment by ninjanomnom** [comment]
Yes though a new pr should probably just be opened for the actual latest version.

**Comment by Vivalas** [comment]
Dunno what this is

**Comment by ninjanomnom** [comment]
Mirrorbot stuff

**Comment by crossedfall** [comment]
Mirrorbot is no longer in use on this repo.

**Pull request closed without merging**
