### PR TITLE
Adds ammo racks and ammunition types + munitions console!

### PR DESCRIPTION
**Pull request by Vivalas**
Also remaps munitions.

image
 
Jesus mapmerge is going to shorten my life expectancy.

Adds 3 different ammunition types

High Explosive (HE) - 5 damage

Shield Piercing (SP) - 1 damage but ignores shields

Smart Homing (SH) - 3 damage but only uses half evasion stat of enemy

Ammo Racks which can be loaded from behind by clicking on them, and dispense from the otherside.

Munitions computer which shows contents of ammo racks and lets you dispense ammo, plus shows status of MAC cannons.

#95

### CODE REVIEW

**Comment by Vivalas** [comment]
What is conflicting with this?

**Comment by Vivalas** [comment]
The only conflicts are in SpaceSHIP.dmm and that has been mapmerged with the latest copy of the map.

**Comment by Vivalas** [comment]
I fixed the conflicts using n++

**Comment by monster860** [comment]
I looked at it in the map editor, looks fine to me.

**Pull request merged**
