### PR TITLE
Contributor Rank - Finale

### PR DESCRIPTION
**Pull request by MASMC**
[Changelogs]: # (Please make a changelog if you're adding, removing or changing content that'll affect players. This includes, but is not limited to, new features, sprites, sounds; balance changes; map edits and important fixes)
[]: # (See here for how to easily make a changelog: https://github.com/tgstation/tgstation/wiki/Changelogs. An example changelog has been provided below. Please edit or remove)

:cl: MASMC
tweak: Tweaked ship logging, to add faction in adminlogs
tweak: Tweaked logging on the emitters, to add a turned on log
fix: Squashed bug that would re-log every time the view vars page was refreshed
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
Bugs, and extra info

### CODE REVIEW

**Comment by Qustinnus** [comment]
put ur name after :cl: u tit

**Comment by MASMC** [comment]
Fixed it :floyddab:

**Comment by MASMC** [comment]
U wot
Travis passed on my fork
Seems like the build froze up or something, but there weren't errors in the code.

**Comment by Qustinnus** [comment]
@monster860 shit broke

**Comment by MASMC** [comment]
I'm just going to like, make a one line change to the admins.txt file in the configs, to get Travis to rebuild, if that's fine?

**Comment by MASMC** [comment]
Never mind on that, I had a change that would be easier on the eyes anyways.

**Pull request merged**
