### PR TITLE
Make Planets Great Again: New Lavaplanet Sprite

### PR DESCRIPTION
**Pull request by ike709**
:cl: keekenox
add: New sprites for lava planets and planet rings.
/:cl:

Adds keek's new lava planet sprite and ring sprites.

image

image

### CODE REVIEW

**Comment by Qustinnus** [comment]
@ike709 The reason I didn't PR this is because the picture goes up higher than the other planets which looks shitter, can you move the picture lower or is that not possible?

**Comment by Qustinnus** [comment]
we dont want bigger sprites though

**Comment by monster860** [comment]
Either way the new rings arent compatible with old planet sprites

**Comment by Qustinnus** [comment]
then wait till the other ones are done i suppose.

**Comment by ike709** [comment]
Guess I'll wait til the other planets are done.

**Pull request closed without merging**
