### PR TITLE
[WIP]Drone System Update: Point Defence Drones

### PR DESCRIPTION
**Pull request by Injazz**
Adds the Drones system that will help ship and it's crew during combat.
Each drone needs to be deployed to space through special drone station placed at Munitions. You can manage drones by new console placed near the drone station.
As an example of what drones can do i added the Point Defence Drone which will act like CIWS turret and will shoot every incoming missile unless it'll spend last bullet in it's storage. MO can reload the drone's storage with special ammo cases (3 of them placed near the console, other obtainable only by adminbus by now)
Defence Drone got 250 bullets with 1% chance to shoot the missile per bullet.
Each drone station can maintain up to 3 drones.

image

TODO:

- [ ] Discuss things
- [ ] Normal sprites (im awful artist, for ammo cases i used .50 sniper case)
- [ ] Make drones and related stuff obtainable by players
- [ ] Make drones being able to be damaged and destroyed

:cl: injazz
add: drone systems that will doing some help to crew during combat
add: defence drone which will fire at enemy rockets
imageadd: drone related sprites(coder-quality)
/:cl:

### CODE REVIEW

**Comment by Stealthkibbler** [comment]
Just put the ammo cases for sale at orbital stations under munitions

Code here
https://github.com/monster860/FTL13/blob/e829377ee614c7c8b7fbba1e6c3b2f0a53522278/code/modules/cargo/packs.dm#L1145

**Comment by Injazz** [comment]
>Also are the enemy ships able to utilize drones and/or drop the parts/ammo for them?
No

**Comment by Stealthkibbler** [comment]
Ah, alright, looking forward to more drone based content to experience in game 👍

**Comment by Signmark** [comment]
@monster860 you can close this PR now because im waiting for combat overhaul

**Pull request closed without merging**
