### PR TITLE
Maps in scrubbers / vents / air alarms

### PR DESCRIPTION
**Pull request by Vivalas**
Didn't use mapmerge because I derped and forgot about it until I was halfway done with scrubbers. Sorry for the massive diff.

This also includes the sniper ammo round changes because I derped twice and did't make a new branch.

:unamused:  :gun:

This should probably be reviewed. I double-checked everything but I may of forgotten some things.

### CODE REVIEW

**Comment by monster860** [comment]
Here's how to fix merge conflict + lack of mapmerge:
1. Copy SpaceSHIP.dmm and put it outside the repo.
2. `git reset --hard HEAD~`
3. `git fetch FTL13`
4. `git merge FTL13/master`
5. Run `Prepare Maps.bat`
6. Copy in the SpaceSHIP.dmm backup with a different name next to the one in the repo.
7. Open both files in a map editor, and reapply your changes from the backup to the new
8. Run `Run Map Merge - TGM.bat`
9. Commit your changes
10. `git push --force origin master`

**Comment by monster860** [comment]
:eyes:

**Comment by Vivalas** [comment]
Okay map merged this, conflicts fixed.

**Comment by monster860** [comment]
You missed a few supply pipes


^^ Munitions button


^^ Entrance to Engineering

**Comment by Vivalas** [comment]
:eyes:

**Comment by monster860** [comment]
Map conflicts.

**Comment by Vivalas** [comment]
Can people, like, kindly hold of on map changes until this is merged? :disappointed:

**Comment by monster860** [comment]
I am officially a git wizard for merging this.

**Comment by CrAzYPiLoT-SS13** [comment]
:clap:

**Comment by Vivalas** [comment]
:eyes:

**Pull request merged**
