### PR TITLE
Removes meme loot

### PR DESCRIPTION
**Pull request by Nickvr628**
Why were these even added? 

:cl:
remove: pulse rifle loot
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
>Yes you can remove the pulse rifle
>Continues to remove other shit I told him not to touch

how about u add back those 2 items and only remove the item you were suppose to remove. cheers.

**Comment by Stealthkibbler** [comment]
how to get stuff removed 101

dunk sec with it.

**Comment by Nickvr628** [comment]
I like having powerful loot Seth, but a 3-fire mode rifle that crits you in 2 hits, can instantly stun you with taser mode, and can break walls with the destroy mode, may be a bit much. Oh, and it has 200 shots per charge.

It was actually supposed to be removed a while ago, but it never was, this was our reminder.

**Comment by Stealthkibbler** [comment]
Floral Somatoray doesn't do any damage at all, it's a botany tool that allows botany to freely mutate the yield and potency of their plants.

**Comment by Qustinnus** [comment]
And a syndie bomb is something useful for current RnD.

**Pull request merged**
