### PR TITLE
Fixes belts (security belts mostly) not having their item overlays before you add/remove an item to them.

### PR DESCRIPTION
**Pull request by kevinz000**
Title. They don't get their items correctly shown unless you take one out and put it back in to force it to update.

:cl: kevinz000
fix: Fixes belts (security belts mostly) not having their item overlays before you add/remove an item to them.
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
travis is complaining

**Comment by kevinz000** [comment]
crap

**Comment by kevinz000** [comment]
oh this is before tg moved everything from New to Initialize let me move it to New

**Comment by kevinz000** [comment]
_should_ work.

**Comment by kevinz000** [comment]
done

**Pull request merged**
