### PR TITLE
Ship name fix

### PR DESCRIPTION
**Pull request by MadmanMartian**
Ships names now have a space between the prefix and the suffix, no more ClownBlaster and TitanSmasher, instead it's Titan Smasher.

:cl: 
fix: Fixes random ship name generation so there is a space between the prefix and the suffix
/:cl:

[why]: # I was playing and saw the ship names coming up as TitanSmasher, FaceBlaster, and the like.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
How on earth did I manage to conflict with that? That's what I was changing!

**Comment by Qustinnus** [comment]
fixed it for ya

**Comment by MadmanMartian** [comment]
Thanks. I must have an old fork I was unaware of

**Comment by LordWalnut** [comment]
image
 
I don't like the look of that.

**Comment by MadmanMartian** [comment]
Oh, it's double spaced for some reason. Odd.

**Comment by NIXC** [comment]
Its because the string has two spaces in it....

Also, the suffix should probably be capitalized in this case.

**Comment by MadmanMartian** [comment]
I was talking about the string having two spaces in it. Could have sworn I only put one.

I'll see what I can do about the suffix

**Pull request merged**
