### PR TITLE
less monkeys

### PR DESCRIPTION
**Pull request by Qustinnus**
:cl: monkey murderer
tweak: Floyd killed about 87.5% of all monkeys in the world.
/:cl:

### CODE REVIEW

**Comment by Vivalas** [comment]
But why

**Comment by Qustinnus** [comment]
because it lags the server to shit?

**Comment by Qustinnus** [comment]
oh and they get aggro as fuck and kill everyone

**Comment by Qustinnus** [comment]
woops accidente

**Pull request merged**
