### PR TITLE
Thrusters

### PR DESCRIPTION
**Pull request by Kmc2000**
[At ecolli's request]

Adds in some decorative thrusters to replace the manky old ones.

They do absolutely nothing for now, this is purely cosmetic

States included for when they are actually added by whoever wants to take that.

:cl: Kmc2000
add: Added some nicer looking ship engines, enjoy!

/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
2/10 no icon states for actual thrusting.

**Comment by Qustinnus** [comment]
jk :^) but i would suck your dick if you add those though

**Comment by Kmc2000** [comment]
>floyddab

No there are thrusting states, i've just not coded them

**Comment by Qustinnus** [comment]
send pic of thrust state

**Comment by Kmc2000** [comment]
https://gyazo.com/3ada15f8f7bf3718dc497d24fbc0fcb6

https://gyazo.com/a1a3bc1845453edd5856b538fd85702d

**Comment by Qustinnus** [comment]
wheres the cool ass flames tho smh

**Pull request merged**
