### PR TITLE
SPESSPODS!

### PR DESCRIPTION
**Pull request by monster860**
:cl: monster860
rscadd: Adds spacepods. Note, they are not mapped in in any way just yet.
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
Yes please. Opens up a lot of cool stuff.

**Comment by Qustinnus** [comment]
We should only have 1 industrial pod with no equipment for transport for miners. RnD should be able to make drills but i think we should leave it at that.

**Comment by CrAzYPiLoT-SS13** [comment]
I don't like this. As discussed before, the crew should be encouraged to stay on the ship and do something constructive, rather than fly around in pods.

**Comment by monster860** [comment]
Im not planning on letting the crew have this, kust miners so that they have a shuttle to transport their goods back to the ship

**Comment by CrAzYPiLoT-SS13** [comment]
Right.

**Pull request merged**
