### PR TITLE
Adds a new lobby theme

### PR DESCRIPTION
**Pull request by ike709**
:cl: ike709
add: A new lobby theme.
/:cl:

https://www.youtube.com/watch?v=Aw3fN3OPk3A

Enjoy.

### CODE REVIEW

**Comment by Qustinnus** [comment]
go away weeb

**Comment by ike709** [comment]
@Qustinnus 

Once upon a time, in New York City in 1941... at this club open to all comers to play, night after night, at a club named "Minston's Play House" in Harlem, they play jazz sessions competing with each other. Young jazz men with a new sense are gathering. At last they created a new genre itself. They are sick and tired of the conventional fixed style jazz. They're eager to play jazz more freely as they wish then... in 2071 in the universe... The bounty hunters, who are gathering in the spaceship "BEBOP", will play freely without fear of risky things. They must create new dreams and films by breaking traditional styles. The work, which becomes a new genre itself, will be called... COWBOY BEBOP

**Comment by Qustinnus** [comment]
i dont speak japanese go away weaboo

**Comment by monster860** [comment]
Don't we have enough lobby musics already?

**Comment by ike709** [comment]
@monster860 no

**Comment by ninjanomnom** [comment]
no such thing as enough lobby music but this one doesn't fit tbh

**Comment by ike709** [comment]
@ninjanomnom It fits way more than the Patton song. Cowboy Bebop is a show about a group of people who travel the solar system doing dangerous jobs for money. That's a ridiculously simplified explanation, anyways.

**Comment by Vivalas** [comment]
I don't think this is very fitting either, the song has no lyrics despite what it may be about. Patton may not be related thematically but it sounds like a triumphant exploration-y song. That's my opinion at least.

**Comment by ninjanomnom** [comment]
At some point we'll probably do a poll type thing for lobby music but for now this doesn't have enough support.

**Pull request closed without merging**
