### PR TITLE
Adds a butterfly knife for the HOS

### PR DESCRIPTION
**Pull request by Kmc2000**
Adds in a butterfly knife for the HOS for maximum crime stoppery.

It spawns in his office so he can grab it easily.

https://i.gyazo.com/763f54ffd7938d11041bac1f79f9d07d.mp4 (twirling animation)

P.S if you can think of a better use for this then put it here

:cl: Kmc2000
add: Gave the head of security a butterfly knife, what could possibly go wrong?

/:cl:

### CODE REVIEW

**Comment by Vivalas** [comment]
:-1: I love the butterfly knife but don't think the HoS should have one by any means. Lethal-only melee weapons for security are rare for a reason. This should be either a traitor item, craftable, or admin spawn.

**Comment by AdamElTablawy** [comment]
KMC did you fucking try porting this to FTL?

WHY?

**Comment by Kmc2000** [comment]
Me "Hey you guys want this? *link*"
Nickvr "WE NEED THAT"

**Comment by Vivalas** [comment]
>Thinking Nick has any influence on the development process :P

**Comment by Funce** [comment]
Is this where we say 'Lol this isn't map merged'

**Comment by CrAzYPiLoT-SS13** [comment]
Ugh, why does the HoS actually need this? Persuade me :^)

**Comment by Vivalas** [comment]
Sorry @Kmc2000 but this really isn't a good idea and you haven't replied.

**Comment by onepunchronan** [comment]
I think the detective needs it...

**Pull request closed without merging**
