### PR TITLE
Two New Syndicate Ships + Salvage Maps

### PR DESCRIPTION
**Pull request by Nickvr628**
:cl: Changes
add: Syndicate Bomber
This ship is a heavy attack ship designed to target and destroy larger prey. It has fast firing weapons but a lower evade chance and weaker defenses. It has zero shields and 14 hull. When salvaged it can provide loot like MAC cannon rounds, EOD equipment, a weapons crate, and a plasma canister.
image

add: Syndicate Smuggler
This is a smaller cargo ship used by syndicate forces to move valuables and people around undetected. It has moderate weapons identical to the Syndicate Skirmisher. Its real strength is in defense. It has a very fast repair time and a shield value of 2, compared to the Skirmisher's 1. It has a lower hull value of 6 however to make up for this. It contains various crates, some MAC cannon rounds, a Phase Cannon, tacticool gear, and a plasma canister. 
image

I have added the ships salvage maps as well as the supporting datum files. This is my first pull request so if I forgot a critical piece of code or file please let me know.

/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
@Nickvr628 Don't use step_x and step_y. You need to go into the map editor and replace the step_ with pixel_ values.

Additionally, the maps need to be converted to TGM using the mapmerging tools.

**Comment by monster860** [comment]
OH yeah, your changelog format is wrong. https://github.com/FTL13/FTL13/wiki/Changelogs

**Comment by monster860** [comment]
Smuggler.dmm still needs mapmerging

**Comment by Nickvr628** [comment]
Ok NOW smuggler.dmm is map merged. That should be all the checkboxs ticked.

**Comment by monster860** [comment]
.....

You have non-mapmerged files in the maps/ship_salvage directory, and mapmerged files in the root directory, this is not correct

Also, the areas on the map do not properly correspond to the datums

Hull components are not the actual ship hull, they are just components that don't contain anything that affect ship operations (Cargo bays, etc)

**Comment by monster860** [comment]
PR has gone stale.

**Pull request closed without merging**
