### PR TITLE
Adds ability for players to lower their head into arms.

### PR DESCRIPTION
**Pull request by The-clown-known-as-Pepe**
Adds dabbing.

http://i.imgur.com/dZsTGIv.png

http://i.imgur.com/b8stKJp.png

### CODE REVIEW

**Comment by nichlas0010** [comment]
image image

**Comment by The-clown-known-as-Pepe** [comment]
@Qustinnus

**Comment by ninjanomnom** [comment]
You can do this already with custom emotes

**Comment by The-clown-known-as-Pepe** [comment]
that is a argument to delete all existing emotes and not change anything ever

**Comment by ninjanomnom** [comment]
Emotes *do* exist that add additional sound or animation. But yes, emotes that don't add anything besides default behavior are pointless

**Comment by The-clown-known-as-Pepe** [comment]
Added sound, animation and effect to dabbing as per "requested".

**Comment by ninjanomnom** [comment]
Self gibbing emotes isn't the kind of thing we do here.

**Comment by The-clown-known-as-Pepe** [comment]
oh then i'll revert it to the original state

**Comment by ninjanomnom** [comment]
As I said in coderbus, you'll need a good reason for this sort of thing to get merged, or convince ecolli or floyd to support it. Code-wise just the base emote has no reason to exist because custom emotes can already be done

**Comment by Qustinnus** [comment]
the chances of me supporting this are as high as your chances of becoming an admin.


read: not very high.

**Comment by ninjanomnom** [comment]
Yeah this isn't happening

**Pull request closed without merging**
