### PR TITLE
Buffs mimes: Species refactor part 1

### PR DESCRIPTION
**Pull request by ike709**
:cl: ike709
tweak: Mimes can no longer break their vow of silence. You're welcome.
/:cl:

[why]: # Fuck you, that's why. Fuck talking mimes too.

### CODE REVIEW

**Comment by NIXC** [comment]
Yes please!

**Comment by ike709** [comment]
tyrannical suppression

**Comment by ninjanomnom** [comment]
you're the one literally trying to suppress free speech ;)

**Comment by Qustinnus** [comment]
if you make it a species it'll break a ton of shit I'd imagine.

**Pull request closed without merging**
