### PR TITLE
Fixes curator spawn points

### PR DESCRIPTION
**Pull request by GoatMonarch**
[Changelogs]: Tweaked the starpoints on the following maps: Aetherwhisp, Feliciana, Ineese, SpaceSHIP, Yacht. 

tweak: Just var edited the name on starpoints from "Librarian" to "Curator"
fix: Curator should now spawn in correctly at round start.

[why]: Referencing issue #3669 were unable to make the scarab map merge correctly, the the butterfly just currupted it self repeatedly.

I'm unable to locate a work around for the Butterfly or Scarab, so somebody fix it my mommy won't let me stay at the computer for more than five minutes. HOOONK!!

### CODE REVIEW

**Comment by GoatMonarch** [comment]
Also pardon for making a new PR for this. I did not seperate the pushes for all the maps seperatly, so I were not exactly able to revert to an earlier point without the scarab.

**Comment by crossedfall** [comment]
@NIXC do you have time to apply the same fix to the scarab and butterfly? If so, can you add it to @GoatMonarch's branch

**Comment by GoatMonarch** [comment]
> @NIXC do you have time to apply the same fix to the scarab and butterfly? If so, can you add it to @GoatMonarch's branch

I have no issue with this, though they said they were unable to do it for some week or so. Though no issue with waiting.

**Comment by crossedfall** [comment]
@GoatMonarch @NIXC Have either of you had time to look into and possibly resolve the issues with the Butterfly and the Scarab?

**Comment by GoatMonarch** [comment]
@crossedfall I am still incapable of using the merge tool on the Scarab or Butterfly for some reason. Considering Aetherwhisp wishes to make a first of april change, we could either work to push it as it is for now, Aetherwhisp makes the change personaly to his map, or just have to adapt once @IndusRobot have done their improvement.

**Pull request merged**
