### PR TITLE
MO gets an age restriction

### PR DESCRIPTION
**Pull request by ike709**
:cl: ike709
tweak: Munitions Officer now has a 10 day age restriction. Same as Bridge Officer.
/:cl:

While the number of days is debatable, I think an age restriction of some amount is definitely justified.

Common mistakes Munitions Officers make that the majority of FTL13 players should hopefully know to avoid:
- Not arming shells before loading them.
- Ejecting armed shells.
- Not knowing oil is the necessary lubricant. I've seen people put in water and welding fuel.
- Spamming the breech open and closed and wasting all the oil
- Not knowing how to replace the actuator / Not knowing the actuator is a thing.
- Not closing the breech.
- Not loading what the WO says to load.

I could go into a much longer list about best practices, but that's full of opinions.

### CODE REVIEW

**Comment by ike709** [comment]
Not to mention the fact that the Munitions Officer is an easy role to troll with via ejecting armed shells.

**Comment by Qustinnus** [comment]
i like

**Comment by ike709** [comment]
Close or merge, please.

**Comment by ike709** [comment]
Close or merge, please. @monster860 @Vivalas

**Pull request merged**
