### PR TITLE
Boarding fix, and removed salvage spawning

### PR DESCRIPTION
**Pull request by TMTIME**
is this a feature or a fix who cares here it is

:cl: TMTIME
fix: fixed boarding
tweak: changed a few boarding only items sprites because they had no icons. 
tweak: Turned off salvage spawning due to the wrecks not being initialised. gotta save the potato from work
tweak: reduced the min number of players to 1 for boarding to start
add: Plenty of warnings that there is a ship with an active Self-Destruct
fix: Swapped some items for ones that have sprites and function the same, and have all defenders a crowbar
/:cl:

[why]: # boarding is o k

A couple boarding only items had no sprites, for now the pirate captain's hardsuit is an engineering one
Reducing the min number of defenders to 1 means that the mode is more likely to activate. Previously, it would require more players to sign up as population got higher, but this becomes an issue when dead people just leave.

Note, that the crew can only board once per system. It's unlikely that they'll ever need to do it twice but this could be changed later

Commits between 13th and 15th were removed later, this is because I started work on this branch with those fixes still applied because I'm shit.

These are only minor issues that can be fixed later
~~todo: later on, add more ships because right now the only ships that spawn these events are pirate clankers (30%) and NT frigates (5% enjoy that ban)~~ Syndicate Bulker added, but will act as a temp map for other ships
todo2: Make ships that were taken over by pirates spawn defenders with pirate gear
todo3: The leader is called Syndicate? Probably an ID thing
todo4: new pirate captain hardsuit sprite

### CODE REVIEW

**Comment by Qustinnus** [comment]
Theres sprites for pirates but I broke em. The filrs should be there tho

**Comment by TMTIME** [comment]
Know where you saved the icons for the steampunk pirate hardsuit? That is the only one that uses a super common sprite (eng hardsuit)

**Comment by Qustinnus** [comment]
not really i kinda forgot ill go check, youll have to fix em tho cuz i fucked them up when i originally added em

**Comment by Qustinnus** [comment]
https://github.com/FTL13/FTL13/pull/814

**Comment by TMTIME** [comment]
Still can't find them. I'll just replace the temp change to a Syndicate engineering one, to reduce FF

**Comment by TMTIME** [comment]
bulker

New Syndicate Bulker boarding map! Set to spawn for most Syndicate ships while maps for them are made with a low % to spawn.

Just so we are clear, that todo list is just stuff I plan to do later, not stuff I want to finish before this gets merged. ~~pelase merge me~~

**Comment by Qustinnus** [comment]
Is this pr done for now then orrr?

**Pull request merged**
