### PR TITLE
The "AAHHHHHH" PR.

### PR DESCRIPTION
**Pull request by Qustinnus**
:cl: Floyd
add: Terror is now a thing. Scream. SCREAM.
/:cl:

It's about time. adds 5 screaming sounds for each gender. only for humans, unless someone gets me quality lizard screaming sounds that dont make me laugh my ass off.

edit: they sound like http://vocaroo.com/i/s0kg4xaw76Cp

### CODE REVIEW

**Comment by monster860** [comment]
I'm sorry but this server is not paradise

*closes pr*

**Comment by AuroranAI** [comment]
appealing to the lowest common denominator: goons. smh
+1

**Comment by Super3222** [comment]
as long as it's not the screams from NML

**Comment by Qustinnus** [comment]
they have screams? send link

**Comment by Super3222** [comment]
https://github.com/WW2-SS13/WW13/blob/master/Interstation-Two-WW2/sound/voice/scream_male.ogg

**Comment by Qustinnus** [comment]
hahaha no mine are worse

**Comment by monster860** [comment]
my reaction to that scream could be characterized by that scream.

**Comment by Qustinnus** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
Against my better judgement this is being merged. Our glorious leader ecolli requests it.

**Pull request merged**
