### PR TITLE
New pressure tank sprites, adds N2O pressure tank and adds Hydrogen skin

### PR DESCRIPTION
**Pull request by stobarico**
All has been described above
All but the hydrogen sprite from VOREstation. The hydrogen one is an original™
Images:
a932999bce8abdb2ae186acc22ee711c

### CODE REVIEW

**Comment by Qustinnus** [comment]
this will clash with the new gasses upstream

**Comment by Belsima** [comment]
vore me daddy

**Comment by stobarico** [comment]
excuse me

**Comment by The-clown-known-as-Pepe** [comment]
stale

**Comment by stobarico** [comment]
@Qustinnus Well, then i can just sprite the canisters for the new gasses when they get added

**Pull request merged**
