### PR TITLE
Adds a few things to bridge, fixes infinite loop with ship repairs

### LINKED ISSUE #38: Infinite loop
```
Infinite loop suspected--switching proc to background.
If it is not an infinite loop, either do 'set background=1' or set world.loop_checks=0.
proc name: repair tick (/datum/subsystem/ship/proc/repair_tick)
  source file: ships.dm,99
  usr: null
  src: Ships (/datum/subsystem/ship)
  call stack:
Ships (/datum/subsystem/ship): repair tick(syndicate skirmisher (/datum/starship/skirmisher))
Ships (/datum/subsystem/ship): process ships()
Ships (/datum/subsystem/ship): fire(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing()
```

@Vivalas

### PR DESCRIPTION
**Pull request by Vivalas**
image

Fixes #38

### CODE REVIEW

**Comment by monster860** [comment]
NEEDS DONUTS.

**Comment by Vivalas** [comment]
Damn how could I forget

**Comment by Vivalas** [comment]
Enough donuts? 
image

**Comment by monster860** [comment]
:ok_hand:

**Comment by monster860** [comment]
Also, put `Fixes #38` in PR description

**Pull request merged**
