### PR TITLE
[WIP] Modular Machine Upgrades (atomized feature from pomf engine)

### PR DESCRIPTION
**Pull request by ninjanomnom**
A machine upgrade system to potentially replace the component system entirely. Experimental for now until all component upgrades are replicated in this system.

### CODE REVIEW

**Comment by ninjanomnom** [comment]
Shhh. Later

**Comment by ike709** [comment]
motherfucker I was about to waste #1000

**Comment by ninjanomnom** [comment]
Alright this is mostly working and worth looking at now.

**Comment by ike709** [comment]
@Vivalas @monster860

**Comment by ninjanomnom** [comment]
This isn't done yet ike

**Comment by ike709** [comment]
image

**Comment by ninjanomnom** [comment]
Worth looking at =/= needs review

**Comment by ninjanomnom** [comment]
woop woop more delays, this needs to be rewritten to use datum components. Will do that after I'm back from visiting family.

**Pull request closed without merging**
