### PR TITLE
[WIP]New smoothing system that is not made by tg coders licking chalkboard erasers (also keek sprites)

### PR DESCRIPTION
**Pull request by monster860**
:cl: monster860
add: New smoothing system1
spriteadd: New wall sprites by keekenox
/:cl:

TODO:
- [ ] Get keek to finish the rwall sprites
- [ ] Get keek to do the normal wall sprites
- [ ] Get keek to do door sprites
- [ ] Get keek to do window sprites
- [ ] Write code for door smoothing because they're SPESHUL

### CODE REVIEW

**Comment by Qustinnus** [comment]
@keekenox stop being hitler and work on this by giving him sprites

**Comment by Qustinnus** [comment]
also @monster860 can you do the airlocks?

**Comment by ninjanomnom** [comment]
let me know when you want a review, sprite code is annoying to work through and you're competent enough to not need my help getting it working

**Comment by crossedfall** [comment]
Closing to focus on 2.0

**Pull request closed without merging**
