### PR TITLE
Adds random ship names

### PR DESCRIPTION
**Pull request by Qustinnus**
:cl: Floyd / Qustinnus
add: Adds random ship names, beware the notorious animechomper.
/:cl:

**The contents of this PR**
I made a simple system that generates a name by getting a prefix and a suffix from 2 different lists and then adding those together, resulting in combos like;
95d1b416941574a1de7717c4a95b72d9

It's very easy to add more words in the helper, and if anyone posts any below I'll try to add them, make sure its not already in the list and please try to make it fit with the other ones.

for example:
prefix:
dream-
hell-

suffix:
-slayer
-bender

### CODE REVIEW

**Comment by ike709** [comment]
You could just have a text file for them y'know.

**Comment by Qustinnus** [comment]
/shrug I just copied what all the other coders did.

**Comment by ike709** [comment]
Did you though? https://github.com/FTL13/FTL13/tree/master/strings

**Comment by Qustinnus** [comment]
https://github.com/FTL13/FTL13/blob/master/code/__HELPERS/names.dm yes

**Comment by ike709** [comment]
Literally none of those in that file have nearly as many choices except maybe codephrases. The big stuff is put in a txt or json file.

**Comment by Qustinnus** [comment]
how 2 fix

**Pull request merged**
