### PR TITLE
[NOPE, I SURRENDER] Ported Overlay Queuing from /tg/

### PR DESCRIPTION
**Pull request by ike709**
:cl: ike709
add: Ported overlay queuing from /tg/.
add: Ported processing.dm from /tg/.
add: Probably created a bunch of overlay bugs.
/:cl:

Credit to cyberboss and some other nerds
Original PR: https://github.com/tgstation/tgstation/pull/23922
Other PRs/stuff:
https://github.com/tgstation/tgstation/pull/24354
https://github.com/tgstation/tgstation/pull/24410
https://github.com/tgstation/tgstation/pull/25210
processing.dm (the version in the Original PR)

inb4 vivalas is confused by code differences

Seriously though this is a pretty big change and it almost certainly broke some stuff, but basic testing reveals no obvious issues.

### CODE REVIEW

**Comment by ike709** [comment]
Hold on I forgot a fix PR. Shouldn't take me 10 minutes.

**Comment by Vivalas** [comment]
>confused by code differences

If there are other PRs that modify the files you are copying please note them too if you're using them as a base for your port :P

**Comment by ike709** [comment]
@Vivalas I told you repeatedly regarding MC Jamboree that any differences between my code and the code in the PRs I linked was a result of me using the latest /tg/ code in place of it and being unable to find the PRs that made the changes.

**Comment by ike709** [comment]
Known issues: Character preview doesn't work. Like at all.

I'm tired though, so I'll fix it tomorrow.

**Comment by ike709** [comment]
Hello darkness my old friend...

**Pull request closed without merging**
