### PR TITLE
Updates ravager wreck

### PR DESCRIPTION
**Pull request by Qustinnus**
🆑 Qustinnus
rscadd: Updates the Ravager Wreck adding more fluff to it.
/🆑

### CODE REVIEW

**Comment by Qustinnus** [comment]
Ugh, can you give me a proper guide on mapmerging? Besides using FastDMM.

**Comment by monster860** [comment]
Before making any changes to the map,  rin Prepare Maps.bat in thd mapmerge directory. Then make yiur edits, save, and do Run Map Merge TGM.bat

**Comment by monster860** [comment]
How to fiz this:

```
git checkout master
```

Then run prepare maps.bat

```
git checkout <name of bfanch>
```

Then run map merge tgm

**Comment by Qustinnus** [comment]
I never set up a map merger so I doubt I have one of those two.

**Pull request merged**
