### PR TITLE
Cargo Changes

### PR DESCRIPTION
**Pull request by DukeDigby**
Added Supply Console to Cargo
Moved Autolathe

### CODE REVIEW

**Comment by Vivalas** [comment]
Pictures?

**Comment by monster860** [comment]
The merge conflicts are real

**Comment by DukeDigby** [comment]
Pic Link: https://gyazo.com/b4b57bf9c23412095481840a117df142

Sorry about the merge conflicts, i'll resolve them as soon as possible. New to Github and havent touched BYOND mapping in a long time.

**Comment by Stealthkibbler** [comment]
The wire and pipe near the door looks deleted, you may want to fix that.

**Pull request closed without merging**
