### PR TITLE
Clothing + Weaponry for New Russia and ION PMC Factions

### PR DESCRIPTION
**Pull request by Weisyl**
Adds 3 new handguns and 2 new assault rifles + 1 new carbine. Along with
this, adds clothing and armor. ALL content ported from Hippie Station
13.

http://puu.sh/s6ZOs/e694a3757f.png

Pistols:

Automag .44 AMT Handgun: A very powerful handgun loaded with .44 AMP
rounds. Has minor armor-penetration and deals very high damage.

C05-R: Based on the Mauser C96. Mag-fed and chambered in .45 ACP.

P053M Luger: Based on the German luger. Mag-fed and chambered in .357
magnum.

Rifles:

AK-922: A modern take on the Russian AKM. Chambered in 7.62x39mm and has
the ability to fire in 3-round bursts. Statistically identical to the
M90 without the grenade launcher. Fits in backpacks.

AKS-740u: Based on the AKS-74u. Chambered in 5.45x39mm and can fire in
3-round bursts. Does somewhat less damage than the AK-922. Fits in
backpacks.

AA-XMG80: An assault rifle developed by Aussec Armory. Chambered in
6.8x43mm caseless. Has fair armor-penetration capability and does
moderate damage per shot. Can fire in 3-shot bursts. Insanely powerful
considering the armor-piercing ability and rather 40 damage per shot.
Practically pulse rifle-tier.

### CODE REVIEW

**Comment by Weisyl** [comment]
I'm curious about when this is getting checked out?

**Comment by CrAzYPiLoT-SS13** [comment]
Didn't even see this PR open. Let me review.

**Comment by CrAzYPiLoT-SS13** [comment]
Only thing is, can we get some pics of the sprites?

**Comment by Weisyl** [comment]
@CrAzYPiLoT-SS13 There's a puush link at the top unless you mean the clothing when dropped as items.

**Pull request merged**
