### PR TITLE
Adds actual FTL themes to the lobby

### PR DESCRIPTION
**Pull request by Qustinnus**
lol don't even give me any shit about this. this music is actually relevant.

🆑 Floyd
Add: Adds an FTL song to the lobby, because you know, we're FTL13.
/🆑

https://youtu.be/nFSHrnqQyV4

### CODE REVIEW

**Comment by ninjanomnom** [comment]
Personally I'd prefer just the second one, the default ftl title theme. First one, the default explore music, seems off for a lobby music. It would be nice to get actual ftl music in though.

**Comment by Qustinnus** [comment]
Mmmhh after the rebase I'm thinking of working on immersion, This'll include 1. Speakers that shout shit the weapon console normally screeches 
2, Background ships and actual firing happening in the background
3. more sounds + reverb
4. preference for having FTL battle music play during battles

**Comment by ike709** [comment]
Yeah I like the second one but the first doesn't fit for a lobby theme.

**Comment by Qustinnus** [comment]
fixed

**Comment by ike709** [comment]
Update the changelog.

**Comment by ninjanomnom** [comment]
Merging this thursday if I dont hear complaints

**Comment by Qustinnus** [comment]
if anyone complains about this we're closing carp fishing and removing the patton march :^)

**Comment by monster860** [comment]
I was going to complain then I clicked on the link and I was like oh its fine

just dont get sued

**Comment by Qustinnus** [comment]
fair use so

**Pull request merged**
