### PR TITLE
Adds homebrew quality meme emojis

### PR DESCRIPTION
**Pull request by stobarico**
as good as it sounds
hyperlul
floyddab
okhand
thonk

### CODE REVIEW

**Comment by Ecolli** [comment]
I think we can devote our time to something a little more "productive" to FTL13. However, since it's done. I personally don't care either way if it gets merged.

**Comment by stobarico** [comment]
It's actually pretty easy to do emojis, literally take a print of something, cut it, put the png into the emoji.dmi file and clear the edges.

**Comment by ninjanomnom** [comment]
>:(

**Comment by Qustinnus** [comment]
i'm sorry :(

**Pull request merged**
