### PR TITLE
Keekenisters, or something like that.

### PR DESCRIPTION
**Pull request by Qustinnus**
:cl:Keekenox (butalsofloyd)
add: new canisters nerds
/:cl:

### CODE REVIEW

**Comment by Raschert0** [comment]
'/:cl:', not ':/cl:'

**Comment by Qustinnus** [comment]
accidente, i was tired.

**Comment by ike709** [comment]
You're supposed to use normal sentence capitalization rules in descriptions @Qustinnus @ninjanomnom

**Comment by Qustinnus** [comment]
https://usatftw.files.wordpress.com/2017/05/spongebob.jpg?w=1000&h=600&crop=1
YoU NeD tU uSE NurMaL SENtencE cApIuTaluzATion

**Pull request merged**
