### PR TITLE
The Great Makeover: Part 1 - "MUH ICONIC SS13" Memes

### PR DESCRIPTION
**Pull request by ike709**
:cl: ike709
tweak: Several things have new sprites. Cameras, security cameras, newscasters, request computers, albums, status display frames, and a few other things I doubt you'll see.
/:cl:

I've begun a grand undertaking: Stealing the best sprites from virtually every codebase and mashing them together. Since people may or may not like these new sprites, I've broken it up into multiple PRs so there's less to review / provide feedback for. Part 1 consists of sprites that I can easily port at midnight without actually editing any icon code. 

### AURORA
request computer
newscaster
fax
cameras
cameras
albums/photos

### VORE/ERIS(?)
status display frame

### I highly recommend opening the images in new tabs so you can actually see them.
Old:
image
New:
image
Old:
image
New:
image
Old:
image
New (The statuses didn't need alterations):
image
Old:
image
New:
image

### CODE REVIEW

**Comment by Qustinnus** [comment]
IDs are iconic to SS13 and I'm not a fan of the new ones

**Comment by ike709** [comment]
@Qustinnus The new ones have been altered.

**Comment by Qustinnus** [comment]
yes but that doesn't change the fact that the old ones are iconic and somewhat nicer imo.

**Comment by Qustinnus** [comment]
I'm against, you can go convince Ecolli.

**Comment by ike709** [comment]
he already said in discord that he likes the sprites, nerd

**Comment by Qustinnus** [comment]
the sprites in general, or the ID sprites in paritcular. go ask him in particular.

**Comment by Ecolli** [comment]
Unfortunately, I DO side with Floyd on this one. While I love the look of the new ID's, I feel they changed form the originals too much =/

**Comment by Qustinnus** [comment]
ICONic

**Comment by ike709** [comment]
Removed the new IDs. I hate all of you.

**Pull request merged**
