### PR TITLE
Redrew the FTL and shieldgen

### PR DESCRIPTION
**Pull request by Kmc2000**
Credits go to:
Crazypilot for lending me his babies (original sprites) to butcher into these amalgamated monstrosities.
Whoever did the original FTL drive - CORRECTION: DEON

Walnut for looking at the sprite

Ecolli for generously giving these for my quote collection:

------------------------------------------------------------------------
Sprite PR with no pictures:

:cl: Kmc2000

imageadd: Made the FTL and shieldgen look nicer 

/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
Pre emptive "NO U" on in the direction of "Adam-El-Tablawy" before he drops a cheeky comment

**Comment by Kmc2000** [comment]
Sniped to meme monster's exacting standards

**Comment by Super3222** [comment]
LOL

**Comment by Nickvr628** [comment]
Me likey

**Pull request merged**
