### PR TITLE
Adds the Patton March as a lobby theme

### PR DESCRIPTION
**Pull request by Vivalas**
Adds the Patton March from the score of the amazing 1970 Patton movie.

https://www.youtube.com/watch?v=HAe40MzBktg for your listening pleasure

:cl: Vivalas
soundadd: New peppy title theme
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
video is gone

**Comment by Vivalas** [comment]
Video is there for me.

**Comment by Qustinnus** [comment]
must be selective racism.

**Comment by Vivalas** [comment]
Fuckin' conflicts man.

**Comment by Vivalas** [comment]
@monster860 Fixes conflicts

**Pull request merged**
