### PR TITLE
adds stechkin back to the security department personel's backpacks

### PR DESCRIPTION
**Pull request by Cdey78**
See title

:cl: Cdey
add: All security members have their stechkins back, excluding detective.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
Please add this to all sec jobs excluding detective

**Comment by Cdey78** [comment]
Detective will be removed anyways

**Comment by Qustinnus** [comment]
which means it woudl create merge conflicts

**Comment by Cdey78** [comment]
I didn't touch detective code..

**Comment by Cdey78** [comment]
I fucked this up, somehow
HOW

**Pull request merged**
